export const topWines:
    Array<Object> =
        [
          {
            "id": "405873",
            "winery_full": "Lewis",
            "wine_full": "Cabernet Sauvignon Napa Valley",
            "vintage": "2013",
            "note":
                "Remarkably elegant and refined for a wine of this size and depth, with tiers of plum, blackberry and currant flavors, as well as subtle touches of black licorice that remain pure and graceful on the long, lingering aftertaste. Drink now through 2028. 1,600 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Napa",
            "score": 95,
            "price": 90,
            "issue_date": "Feb 29, 2016",
            "top100_year": 2016,
            "top100_rank": 1
          },
          {
            "id": "424528",
            "winery_full": "Domaine Serene",
            "wine_full": "Chardonnay Dundee Hills Evenstad Reserve",
            "vintage": "2014",
            "note":
                "Focused and expressive, this is layered with wet stone, tangy citrus, pear and green guava flavors that swirl through an expansive finish, gaining momentum and extra dimensions with each sip. Drink now through 2024. 2,000 cases made.",
            "taster_initials": "HS",
            "color": "white",
            "country": "Oregon",
            "region": "Oregon",
            "score": 95,
            "price": 55,
            "issue_date": "Dec 31, 2016",
            "top100_year": 2016,
            "top100_rank": 2
          },
          {
            "id": "420777",
            "winery_full": "Beaux FrÃ¨res",
            "wine_full": "Pinot Noir Ribbon Ridge The Beaux FrÃ¨res Vineyard",
            "vintage": "2014",
            "note":
                "Supple, expressive and multilayered, exhibiting flavors of plum, currant, pomegranate and violet that come together harmoniously, persisting into the long and exceptionally well-balanced finish. Drink now through 2024. 2,405 cases made.",
            "taster_initials": "HS",
            "color": "red",
            "country": "Oregon",
            "region": "Oregon",
            "score": 95,
            "price": 90,
            "issue_date": "Oct 31, 2016",
            "top100_year": 2016,
            "top100_rank": 3
          },
          {
            "id": "408002",
            "winery_full": "ChÃ¢teau Climens",
            "wine_full": "Barsac",
            "vintage": "2013",
            "note":
                "There'Âs loads here, with apricot, nectarine and clementine flavors stitched with a racy orange zest note to give energy, while tropical papaya and mango flavors add a sublimely creamy edge. The finish sails on and on, coating the palate with a porcelain feel, while an echo of bitter almond lingers effortlessly, like a lace curtain hanging on an endless breeze. Stunning. Best from 2018 through 2043. 1,417 cases made.",
            "taster_initials": "JM",
            "color": "dessert",
            "country": "France",
            "region": "Bordeaux",
            "score": 97,
            "price": 68,
            "issue_date": "Mar 31, 2016",
            "top100_year": 2016,
            "top100_rank": 4
          },
          {
            "id": "413676",
            "winery_full": "Produttori del Barbaresco",
            "wine_full": "Barbaresco Asili Riserva",
            "vintage": "2011",
            "note":
                "Intense aromas of cherry, rose, licorice and tar pick up tobacco, spice and mineral elements on the palate. Concentrated, yet elegant and expressive, with more to give. Ends with a long aftertaste of fruit, underbrush and mineral. Best from 2018 through 2032. 1,110 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Piedmont",
            "score": 96,
            "price": 59,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 5
          },
          {
            "id": "415560",
            "winery_full": "Orin Swift",
            "wine_full": "Machete California",
            "vintage": "2014",
            "note":
                "Generous and expressive, big and brawny, this offers a mouthful of tannins but also brims with flavors and aromas, including Earl Grey tea, dark chocolate, dried violet and toasted gingerbread. Rich notes of plum and black cherry are balanced by forest floor and earth accents, which linger on the long finish. Petite Sirah, Syrah and Grenache. Drink now through 2030. 15,500 cases made.",
            "taster_initials": "MW",
            "color": "red",
            "country": "California",
            "region": "Other California",
            "score": 94,
            "price": 48,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 6
          },
          {
            "id": "405122",
            "winery_full": "Ridge",
            "wine_full": "Monte Bello Santa Cruz Mountains",
            "vintage": "2012",
            "note":
                "A beautifully structured wine, with firm acidity and tannins that show grip and grit amid a core of dense, tense currant and blackberry fruit, turning juicy. Those seeking classic old-school Cabernet will embrace this. Cellaring for five to seven years is the right approach. Cabernet Sauvignon, Merlot, Cabernet Franc and Petit Verdot. Best from 2020 through 2035. 5,243 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Bay Area/Central Coast",
            "score": 94,
            "price": 175,
            "issue_date": "Feb 29, 2016",
            "top100_year": 2016,
            "top100_rank": 7
          },
          {
            "id": "416751",
            "winery_full": "Antinori",
            "wine_full": "Toscana Tignanello",
            "vintage": "2013",
            "note":
                "Aromas of graphite, smoke and tobacco introduce the cherry flavor in this expressive, focused red. Firm tannins and lively acidity balance the fruit and purity, while herbal, spice and mineral elements all gather steam as this plays out on the long finish. Sangiovese, Cabernet Sauvignon and Cabernet Franc. Best from 2017 through 2027. 2,500 cases imported.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 94,
            "price": 105,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 8
          },
          {
            "id": "407841",
            "winery_full": "ChÃ¢teau Smith-Haut-Lafitte",
            "wine_full": "Pessac-LÃ©ognan White",
            "vintage": "2013",
            "note":
                "This has a gorgeous feel, with opulent fruit offset by racy herb notes and acidity, showing lemon sherbet, shortbread and white peach flavors backed by a salted butterÂâ and tarragon-laced finish, with hints of talc and fennel skittering in the background. Seriously long and still a touch youthful on the finish, this is one for the cellar. Sauvignon Blanc, Sauvignon Gris and SÃ©millon. Best from 2017 through 2023. 2,500 cases made.",
            "taster_initials": "JM",
            "color": "white",
            "country": "France",
            "region": "Bordeaux",
            "score": 96,
            "price": 106,
            "issue_date": "Mar 31, 2016",
            "top100_year": 2016,
            "top100_rank": 9
          },
          {
            "id": "412815",
            "winery_full": "Hartford Family",
            "wine_full": "Zinfandel Russian River Valley Old Vine",
            "vintage": "2014",
            "note":
                "Plump and fleshy, with a dense core of focused tannins and lively acidity. Aromas of ripe black raspberry, anise and licorice open to layered, slightly jammy flavors of black cherry, blueberry pie and smoky cracked pepper. Drink now through 2024. 2,200 cases made.",
            "taster_initials": "TF",
            "color": "red",
            "country": "California",
            "region": "Sonoma",
            "score": 93,
            "price": 38,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 10
          },
          {
            "id": "416499",
            "winery_full": "Hamilton Russell",
            "wine_full": "Chardonnay Hemel-en-Aarde Valley",
            "vintage": "2015",
            "note":
                "Ripe and rippling with tension, featuring Jonagold apple, white peach, mirabelle plum and honeysuckle notes coiled at the core. Accents of heather and hazelnut extend slowly through the citrus oilÂ and mineral-edged finish. Best from 2017 through 2022. 2,700 cases imported.",
            "taster_initials": "JM",
            "color": "white",
            "country": "South Africa",
            "region": "Walker Bay",
            "score": 94,
            "price": 37,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 11
          },
          {
            "id": "421799",
            "winery_full": "Abadia Retuerta",
            "wine_full":
                "ViÃ±o de la Tierra de Castilla y LeÃ³n SelecciÃ³n Especial Sardon de Duero",
            "vintage": "2012",
            "note":
                "A polished texture carries harmonious flavors of black cherry, cola, licorice and mineral in this focused red. Well-integrated tannins and balsamic acidity lend this a balanced structure. Reserved but deep. Drink now through 2022. 31,150 cases made.",
            "taster_initials": "TM",
            "color": "red",
            "country": "Spain",
            "region": "Spain",
            "score": 93,
            "price": 28,
            "issue_date": "Nov 30, 2016",
            "top100_year": 2016,
            "top100_rank": 12
          },
          {
            "id": "415224",
            "winery_full": "Reynvaan",
            "wine_full": "Syrah Walla Walla Valley In The Rocks",
            "vintage": "2013",
            "note":
                "Supple and expressive, this opens up like a giant flower, spreading the dark plum, blackberry, crÃ¨me fraÃ®che and spice flavors throughout the seamless whole. The finish sails on against barely noticeable tannins. This has tremendous power, but feels like it's floating. Drink now through 2025. 602 cases made.",
            "taster_initials": "HS",
            "color": "red",
            "country": "Washington",
            "region": "Washington",
            "score": 97,
            "price": 70,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 13
          },
          {
            "id": "416048",
            "winery_full": "Carlisle",
            "wine_full": "Zinfandel Russian River Valley Montafi Ranch",
            "vintage": "2014",
            "note":
                "Zinfandel doesn't get much better than this. Rich aromas of black raspberry and orange zest open to balanced, complex and luxurious flavors of blackberry, mint and baking spices. A knockout. Drink now through 2027. 871 cases made.",
            "taster_initials": "TF",
            "color": "red",
            "country": "California",
            "region": "Sonoma",
            "score": 96,
            "price": 47,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 14
          },
          {
            "id": "416118",
            "winery_full": "M. Marengo",
            "wine_full": "Barolo Bricco delle Viole",
            "vintage": "2012",
            "note":
                "Shows fine integration between fruit and wood, with sweet cherry and strawberry flavors matched to spice, floral and briar accents. Fresh, vibrant and firmly structured, this is long on the fruit-, spice- and mineral-tinged finish. Shows fine balance and expression. Best from 2018 through 2032. 333 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Piedmont",
            "score": 94,
            "price": 53,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 15
          },
          {
            "id": "407995",
            "winery_full": "ChÃ¢teau Coutet",
            "wine_full": "Barsac",
            "vintage": "2013",
            "note":
                "Unctuous and ripe, showing mouthfilling flavors of almond cream, ginger, heather honey and apricot, this will need time to unwind fully, but when it does, expect more pineapple, maple and singed orange notes, as this has some depth and power in reserve, as well as more than enough cut for balance. A beauty in the making. Best from 2018 through 2038. 2,833 cases made.",
            "taster_initials": "JM",
            "color": "dessert",
            "country": "France",
            "region": "Bordeaux",
            "score": 96,
            "price": 41,
            "issue_date": "Mar 31, 2016",
            "top100_year": 2016,
            "top100_rank": 16
          },
          {
            "id": "411322",
            "winery_full": "Merry Edwards",
            "wine_full": "Sauvignon Blanc Russian River Valley",
            "vintage": "2014",
            "note":
                "Succulent, lush and rich, with fleshy mango, melon and peach flavors up front, leading to a core of pineapple, lemon and honeysuckle notes. The smoky edge and nervy acidity weave in and out, giving this a fresh finish. Drink now. 9,500 cases made.",
            "taster_initials": "MW",
            "color": "white",
            "country": "California",
            "region": "Sonoma",
            "score": 93,
            "price": 32,
            "issue_date": "May 31, 2016",
            "top100_year": 2016,
            "top100_rank": 17
          },
          {
            "id": "412962",
            "winery_full": "Condado de Haza",
            "wine_full": "Ribera del Duero",
            "vintage": "2012",
            "note":
                "This rich red shows a deep core of plum, bramble and mineral, with notes of loam and game that impart a savory character. Solid tannins support a thick texture, while balsamic acidity keeps this balanced. Austere but harmonious. Drink now through 2024. 35,000 cases made.",
            "taster_initials": "TM",
            "color": "red",
            "country": "Spain",
            "region": "Spain",
            "score": 93,
            "price": 25,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 18
          },
          {
            "id": "410620",
            "winery_full": "Arcanum",
            "wine_full": "Toscana Il Fauno",
            "vintage": "2012",
            "note":
                "A polished, flavorful red, boasting floral, black currant, raspberry and spice flavors. Firm yet harmonious, with the fine aftertaste lingering with fruit, iron, tobacco and tea elements. Merlot, Cabernet Franc, Cabernet Sauvignon and Petit Verdot. Drink now through 2024. 11,829 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 93,
            "price": 30,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 19
          },
          {
            "id": "407697",
            "winery_full": "Turley",
            "wine_full": "Zinfandel Paso Robles Ueberroth Vineyard",
            "vintage": "2013",
            "note":
                "This potent red is loaded with personality, featuring aromas of smoky black raspberry and licorice that open to complex, dense flavors of dried cherry, cracked pepper beef and grilled herb. The tannins are big and framed by loamy mineral details. Drink now through 2028. 1,800 cases made.",
            "taster_initials": "TF",
            "color": "red",
            "country": "California",
            "region": "South Coast",
            "score": 94,
            "price": 48,
            "issue_date": "Mar 31, 2016",
            "top100_year": 2016,
            "top100_rank": 20
          },
          {
            "id": "418902",
            "winery_full": "Sparkman",
            "wine_full": "Cabernet Sauvignon Columbia Valley Holler",
            "vintage": "2013",
            "note":
                "Dense and focused, with a tangy edge to the dark plum and currant flavors, hinting at stony mineral and dusky spice flavors as the finish persists impressively against fine tannins. Best from 2018 through 2023. 912 cases made.",
            "taster_initials": "HS",
            "color": "red",
            "country": "Washington",
            "region": "Washington",
            "score": 94,
            "price": 32,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 21
          },
          {
            "id": "411404",
            "winery_full": "Cune",
            "wine_full": "Rioja Gran Reserva",
            "vintage": "2010",
            "note":
                "This generous red shows a traditional character, with leafy, dried herb, tea and spice notes framing dried cherry, licorice and leather flavors. Firm tannins and balsamic acidity impart structure, and this shows plenty of depth, with a juicy, spicy finish. Drink now through 2025. 600 cases imported.",
            "taster_initials": "TM",
            "color": "red",
            "country": "Spain",
            "region": "Spain",
            "score": 94,
            "price": 33,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 22
          },
          {
            "id": "411737",
            "winery_full": "Mocali",
            "wine_full": "Brunello di Montalcino",
            "vintage": "2011",
            "note":
                "This lively red exhibits cherry, strawberry, eucalyptus, tobacco and mineral flavors. The firm tannins work in tandem with the bright acidity, leaving a long, refreshing finish that echoes the fruit, earth and savory elements. Best from 2018 through 2028. 3,800 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 93,
            "price": 40,
            "issue_date": "Jun 15, 2016",
            "top100_year": 2016,
            "top100_rank": 23
          },
          {
            "id": "424335",
            "winery_full": "DuMOL",
            "wine_full": "Syrah Russian River Valley",
            "vintage": "2014",
            "note":
                "This is plush, rich and impeccably structured, with floral blueberry and raspberry aromas accented by smoky pepper and complex, expressive flavors that combine mineral-tinged tannins with plump fruit. Best from 2018 through 2030. 1,100 cases made.",
            "taster_initials": "TF",
            "color": "red",
            "country": "California",
            "region": "Sonoma",
            "score": 94,
            "price": 55,
            "issue_date": "Dec 31, 2016",
            "top100_year": 2016,
            "top100_rank": 24
          },
          {
            "id": "420667",
            "winery_full": "Villa Pillo",
            "wine_full": "Toscana Borgoforte",
            "vintage": "2014",
            "note":
                "Enticing aromas of violet, black currant and rosemary are accented by licorice and tobacco flavors in this fluid and harmonious red, with fine tannins gracing the long finish. Sangiovese, Cabernet Sauvignon and Merlot. Drink now through 2022. 12,500 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 91,
            "price": 12,
            "issue_date": "Nov 15, 2016",
            "top100_year": 2016,
            "top100_rank": 25
          },
          {
            "id": "411364",
            "winery_full": "Bodegas y ViÃ±edos Maurodos",
            "wine_full": "Toro San RomÃ¡n",
            "vintage": "2012",
            "note":
                "The polished texture masks depth and muscle in this powerful red, which shows blackberry, anise, tar and mineral flavors, with spicy and floral highlights. Firm tannins and fresh acidity lend good balance. Expressive, in an austere way. Drink now through 2027. 7,750 cases made.",
            "taster_initials": "TM",
            "color": "red",
            "country": "Spain",
            "region": "Spain",
            "score": 95,
            "price": 65,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 26
          },
          {
            "id": "424316",
            "winery_full": "Matthews",
            "wine_full": "Claret Columbia Valley",
            "vintage": "2013",
            "note":
                "Firm and focused, with crinkly tannins around a sleek core of blackberry, currant and plum flavors that keep singing on the expressive finish. This has room to grow. Cabernet Sauvignon, Cabernet Franc, Merlot, Malbec and Petit Verdot. Drink now through 2022. 2,129 cases made.",
            "taster_initials": "HS",
            "color": "red",
            "country": "Washington",
            "region": "Washington",
            "score": 93,
            "price": 40,
            "issue_date": "Dec 31, 2016",
            "top100_year": 2016,
            "top100_rank": 27
          },
          {
            "id": "412143",
            "winery_full": "Domaine Carneros",
            "wine_full": "Brut Carneros Ultra",
            "vintage": "2011",
            "note":
                "Captivating aromas of Asian pear, mature apple and fresh ginger open to complex and polished flavors of brioche, spicy hazelnut and crÃ¨me brÃ»lÃ©e. Drink now through 2018. 2,700 cases made.",
            "taster_initials": "TF",
            "color": "sparkling",
            "country": "California",
            "region": "Carneros",
            "score": 93,
            "price": 42,
            "issue_date": "Jun 15, 2016",
            "top100_year": 2016,
            "top100_rank": 28
          },
          {
            "id": "418276",
            "winery_full": "Tenuta di Trinoro",
            "wine_full": "Toscana Le Cupole",
            "vintage": "2014",
            "note":
                "Alluring scents of ripe cherry, mulberry and fresh herbs complement concentrated flavors of cherry and sweet spice in this red. Offers a backbone of mouthcoating tannins and remains integrated as the finish lingers. Merlot, Cabernet Franc and Cabernet Sauvignon. Best from 2018 through 2027. 4,600 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 93,
            "price": 27,
            "issue_date": "Oct 31, 2016",
            "top100_year": 2016,
            "top100_rank": 29
          },
          {
            "id": "410585",
            "winery_full": "Mollydooker",
            "wine_full": "Shiraz McLaren Vale Carnival of Love",
            "vintage": "2014",
            "note":
                "Bold, expressive, velvety and generous, with ripe cherry and plum flavors at the core. Complex details of vanilla bean, licorice, Earl Grey tea and gingerbread explode on the long finish. Drink now through 2030. 1,467 cases made.",
            "taster_initials": "MW",
            "color": "red",
            "country": "Australia",
            "region": "Australia",
            "score": 95,
            "price": 75,
            "issue_date": "May 31, 2016",
            "top100_year": 2016,
            "top100_rank": 30
          },
          {
            "id": "419117",
            "winery_full": "Tenshen",
            "wine_full": "White Central Coast",
            "vintage": "2015",
            "note":
                "This expressive white is aromatic and juicy, featuring a rich, ripe, fleshy core of apricot and peach flavors, with accents of vanilla bean, honeysuckle and melon. A spicy note lingers on the long finish. Viognier, Roussanne, Grenache Blanc and Chardonnay. Drink now. 5,100 cases made.",
            "taster_initials": "MW",
            "color": "white",
            "country": "California",
            "region": "Other California",
            "score": 92,
            "price": 20,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 31
          },
          {
            "id": "415240",
            "winery_full": "Intrinsic",
            "wine_full": "Cabernet Sauvignon Columbia Valley",
            "vintage": "2014",
            "note":
                "Firm in texture, brimming with raspberry, black cherry, violet and herb flavors that come together harmoniously on the finish against refined tannins. Offers presence and persistence. Best from 2018 through 2024. 30,000 cases made.",
            "taster_initials": "HS",
            "color": "red",
            "country": "Washington",
            "region": "Washington",
            "score": 92,
            "price": 22,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 32
          },
          {
            "id": "410527",
            "winery_full": "Concha y Toro",
            "wine_full": "Cabernet Sauvignon Puente Alto Don Melchor",
            "vintage": "2012",
            "note":
                "Suave and refined, with rich, dense flavors of dried berry, dark plum, rose petal and bramble. Offers fine-grained tannins and accents of green olive. Finishes with hints of hot stone, dried beef and white pepper. Complex. Drink now through 2022. 7,400 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Chile",
            "region": "Maipo",
            "score": 95,
            "price": 125,
            "issue_date": "May 31, 2016",
            "top100_year": 2016,
            "top100_rank": 33
          },
          {
            "id": "418609",
            "winery_full": "John Duval",
            "wine_full": "Plexus Red Barossa Valley",
            "vintage": "2014",
            "note":
                "A sophisticated, spicy mix of date bread, cherry compote and clove flavors. Plump and velvety, with persistence and harmony on the finish. Shiraz, Grenache and MourvÃ¨dre. Drink now through 2026. 1,000 cases imported.",
            "taster_initials": "MW",
            "color": "red",
            "country": "Australia",
            "region": "Australia",
            "score": 93,
            "price": 40,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 34
          },
          {
            "id": "409435",
            "winery_full": "Sojourn",
            "wine_full": "Pinot Noir Sonoma Coast Gap's Crown Vineyard",
            "vintage": "2014",
            "note":
                "Lightly aromatic, but rich and layered, this offers excellent density and depth, with fine-grained tannic grip and a long, persistent finish that keeps flashing the core flavors. Drink now through 2020. 1,350 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Sonoma",
            "score": 94,
            "price": 59,
            "issue_date": "Apr 30, 2016",
            "top100_year": 2016,
            "top100_rank": 35
          },
          {
            "id": "405265",
            "winery_full": "G.D. Vajra",
            "wine_full": "Barolo Bricco delle Viole",
            "vintage": "2011",
            "note":
                "Graphite and iron aromas lead off, with cherry, floral, licorice, tea and underbrush flavors. This is intense, vibrant and resonant on the long, fruit- and mineral-infused aftertaste. Best from 2019 through 2032. 1,500 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Piedmont",
            "score": 95,
            "price": 70,
            "issue_date": "Apr 30, 2016",
            "top100_year": 2016,
            "top100_rank": 36
          },
          {
            "id": "415225",
            "winery_full": "Cayuse",
            "wine_full": "Syrah Walla Walla Valley Cailloux Vineyard",
            "vintage": "2013",
            "note":
                "Broad and expressive, playing the cherry, raspberry and pear notes against fine tannins. Picks up tobacco, tar and mineral notes as the finish sails on. Has terrific presence without weight. Drink now through 2025. 846 cases made.",
            "taster_initials": "HS",
            "color": "red",
            "country": "Washington",
            "region": "Washington",
            "score": 96,
            "price": 80,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 37
          },
          {
            "id": "413071",
            "winery_full": "Ramey",
            "wine_full": "Chardonnay Russian River Valley Ritchie Vineyard",
            "vintage": "2013",
            "note":
                "Shows amazing vibrancy and purity of flavor, brimming with juicy, lemon-scented green apple, white peach and tangerine notes, enlivened by zesty acidity and a long, persistent aftertaste that maintains focus and depth. Drink now through 2020. 1,250 cases made.",
            "taster_initials": "JL",
            "color": "white",
            "country": "California",
            "region": "Sonoma",
            "score": 94,
            "price": 65,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 38
          },
          {
            "id": "405675",
            "winery_full": "Bodegas Borsao",
            "wine_full": "Garnacha Campo de Borja Tres Picos",
            "vintage": "2014",
            "note":
                "A plush texture masks the firm structure of this red, as blackberry and boysenberry flavors mingle with notes of toast, menthol and mineral, backed by well-integrated tannins and juicy acidity. A modern style, with balance and depth. Drink now through 2020. 10,000 cases made.",
            "taster_initials": "TM",
            "color": "red",
            "country": "Spain",
            "region": "Spain",
            "score": 91,
            "price": 18,
            "issue_date": "Mar 31, 2016",
            "top100_year": 2016,
            "top100_rank": 39
          },
          {
            "id": "408441",
            "winery_full": "Fattoria di Felsina",
            "wine_full": "Chianti Classico Berardenga",
            "vintage": "2013",
            "note":
                "Rich and sumptuous, boasting pure flavors of cherry and raspberry, matched to a juicy texture. There are plenty of tannins neatly folded into the overall structure, with hints of mineral and tea on the long, expansive finish. Best from 2017 through 2024. 15,000 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 92,
            "price": 26,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 40
          },
          {
            "id": "412731",
            "winery_full": "Kono",
            "wine_full": "Sauvignon Blanc Marlborough",
            "vintage": "2015",
            "note":
                "This refreshing white offers a clear, focused mix of passion fruit, lime, mango and green apple flavors on a light, smooth body. Finishes with a succulent juiciness, showing echoes of lemon verbena. Drink now. 80,000 cases made.",
            "taster_initials": "MW",
            "color": "white",
            "country": "New Zealand",
            "region": "New Zealand",
            "score": 90,
            "price": 12,
            "issue_date": "Jun 15, 2016",
            "top100_year": 2016,
            "top100_rank": 41
          },
          {
            "id": "422051",
            "winery_full": "ViÃ±a Montes",
            "wine_full": "Cabernet Sauvignon Colchagua Valley Classic Series",
            "vintage": "2014",
            "note":
                "There's minerally freshness to the ripe dark plum, blackberry and cherry flavors, with peppery hints. Well-structured and crisp midpalate, featuring Asian spice and black fig notes on the finish. Drink now through 2020. 50,000 cases imported.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Chile",
            "region": "Rapel",
            "score": 90,
            "price": 13,
            "issue_date": "Dec 31, 2016",
            "top100_year": 2016,
            "top100_rank": 42
          },
          {
            "id": "417322",
            "winery_full": "St.-Cosme",
            "wine_full": "CÃ´tes du RhÃ´ne",
            "vintage": "2015",
            "note":
                "Ripe, with vivid blueberry and boysenberry fruit, harnessed on the back end by a bold graphite edge. Anise and violet notes add range. Drink now through 2019. 25,000 cases made.",
            "taster_initials": "JM",
            "color": "red",
            "country": "France",
            "region": "Southern RhÃ´ne",
            "score": 91,
            "price": 16,
            "issue_date": "Nov 15, 2016",
            "top100_year": 2016,
            "top100_rank": 43
          },
          {
            "id": "419776",
            "winery_full": "Caymus",
            "wine_full": "Cabernet Sauvignon Napa Valley Special Selection",
            "vintage": "2013",
            "note":
                "This zeroes in on a rich, hedonistic core of wild berry, blackberry, plum and currant flavors, with a graceful, elegant mouthfeel and supple, caressing tannins. The long and powerful yet refined aftertaste keeps reverberating fruit generosity while maintaining Cabernet's strength of personality. Drink now through 2030. 21,249 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Napa",
            "score": 95,
            "price": 160,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 44
          },
          {
            "id": "424596",
            "winery_full": "Charles Smith",
            "wine_full":
                "Riesling Ancient Lakes Of Columbia Valley Kung Fu Girl Evergreen",
            "vintage": "2015",
            "note":
                "Tangy and zingy, with lively acidity that balances against gobs of ripe pear and apricot flavors, carrying through the long, lime-accented finish. Drink now through 2020. 160,000 cases made.",
            "taster_initials": "HS",
            "color": "white",
            "country": "Washington",
            "region": "Washington",
            "score": 90,
            "price": 12,
            "issue_date": "Dec 31, 2016",
            "top100_year": 2016,
            "top100_rank": 45
          },
          {
            "id": "409785",
            "winery_full": "Quinta de Cabriz",
            "wine_full": "DÃ£o",
            "vintage": "2014",
            "note":
                "A crisp and minerally red, with concentrated flavors of dark cherry, roasted plum and dried raspberry, layered with rich, spicy notes. White chocolate details show on the finish, accented by hints of pepper. Drink now through 2020. 208,000 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Portugal",
            "region": "Portugal",
            "score": 90,
            "price": 10,
            "issue_date": "Jun 15, 2016",
            "top100_year": 2016,
            "top100_rank": 46
          },
          {
            "id": "418885",
            "winery_full": "Hall",
            "wine_full":
                "Cabernet Sauvignon Napa Valley Eighteen Seventy-Three",
            "vintage": "2013",
            "note":
                "Ultrarich, layered and tightly focused on a dense core of meaty blackberry, currant, loamy earth, anise, crushed rock and graphite notes. For all the flavor and depth, this features a persistent finish that folds in smoky, toasty oak, adding an extra dimension of texture, flavor and aroma. Drink now through 2028. 4,723 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Napa",
            "score": 94,
            "price": 80,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 47
          },
          {
            "id": "420670",
            "winery_full": "Fournier PÃ¨re & Fils",
            "wine_full": "Sancerre Les Belles Vignes",
            "vintage": "2015",
            "note":
                "Very pure and chiseled, with gooseberry, straw and flint flavors tightly coiled, driven by a mouthwatering fleur de sel note through the long, bone-dry finish, which is built on minerality. Drink now through 2021. 7,000 cases imported.",
            "taster_initials": "JM",
            "color": "white",
            "country": "France",
            "region": "Loire",
            "score": 92,
            "price": 26,
            "issue_date": "Nov 30, 2016",
            "top100_year": 2016,
            "top100_rank": 48
          },
          {
            "id": "411821",
            "winery_full": "Renieri",
            "wine_full": "Brunello di Montalcino Riserva",
            "vintage": "2010",
            "note":
                "This is reminiscent of a fine Burgundy, showing berry, fading cherry, spice and chalky mineral notes. Juicy and elegant, firm yet harmonious, this lingers with a long, complex aftertaste. Best from 2018 through 2033. 1,000 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 96,
            "price": 100,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 49
          },
          {
            "id": "415729",
            "winery_full": "Real Companhia Velha",
            "wine_full": "Douro Evel Red",
            "vintage": "2014",
            "note":
                "A lithe red, with good cut to the red berry and plum tart flavors, supported by fresh acidity, showing notes of pepper and hot stone on the minerally finish. Offers impressive purity to the fruit components. Drink now through 2020. 60,000 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Portugal",
            "region": "Portugal",
            "score": 90,
            "price": 13,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 50
          },
          {
            "id": "406103",
            "winery_full": "M. Chapoutier",
            "wine_full":
                "CÃ´tes du Roussillon-Villages Les Vignes de Bila-Haut",
            "vintage": "2014",
            "note":
                "This red is supple and fresh, showing a mix of dark berry, plum, herbal tea and peppery flavors. Lightly grippy tannins frame the licorice- and mineral-accented finish. Drink now through 2018. 55,000 cases made.",
            "taster_initials": "GS",
            "color": "red",
            "country": "France",
            "region": "Languedoc-Roussillon",
            "score": 90,
            "price": 15,
            "issue_date": "Mar 31, 2016",
            "top100_year": 2016,
            "top100_rank": 51
          },
          {
            "id": "422912",
            "winery_full": "Bodegas Palacios Remondo",
            "wine_full": "Rioja La Montesa Crianza",
            "vintage": "2013",
            "note":
                "A thick texture carries plum tart, orange peel, toasted vanilla and anise flavors in this ripe version, balanced by juicy acidity. The spicy, berry-scented finish is long and pure. Drink now through 2023. 10,800 cases imported.",
            "taster_initials": "TM",
            "color": "red",
            "country": "Spain",
            "region": "Spain",
            "score": 91,
            "price": 20,
            "issue_date": "Dec 15, 2016",
            "top100_year": 2016,
            "top100_rank": 52
          },
          {
            "id": "419502",
            "winery_full": "Familia Zuccardi",
            "wine_full": "Cabernet Sauvignon Uco Valley Q",
            "vintage": "2013",
            "note":
                "A refined and savory red, featuring notes of white pepper to the cherry and crushed red plum flavors. Lengthens out on the palate, with medium-grained tannins. Silky finish. Drink now through 2020. 7,500 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Argentina",
            "region": "Mendoza",
            "score": 91,
            "price": 20,
            "issue_date": "Oct 31, 2016",
            "top100_year": 2016,
            "top100_rank": 53
          },
          {
            "id": "407182",
            "winery_full": "Fritz Hasselbach",
            "wine_full": "Riesling QbA Rheinhessen Fritz's",
            "vintage": "2014",
            "note":
                "Redolent of white raspberry jam and mint, this white is lush and creamy midpalate, with crackling acidity. The off-dry finish delivers honey and spice details. Drink now through 2018. 20,000 cases made.",
            "taster_initials": "KM",
            "color": "white",
            "country": "Germany",
            "region": "Germany",
            "score": 90,
            "price": 14,
            "issue_date": "May 31, 2016",
            "top100_year": 2016,
            "top100_rank": 54
          },
          {
            "id": "417412",
            "winery_full": "GÃ©rard Bertrand",
            "wine_full": "Grenache-Syrah-MourvÃ¨dre CorbiÃ¨res",
            "vintage": "2014",
            "note":
                "Full-bodied and powerful, with decadent layers of raspberry compote, kirsch and red plum notes that are met with savory details of herb and cured meat. Offers a tangy, hot stoneÂâaccented finish. Drink now through 2025. 18,000 cases made.",
            "taster_initials": "GS",
            "color": "red",
            "country": "France",
            "region": "Languedoc-Roussillon",
            "score": 90,
            "price": 19,
            "issue_date": "Nov 15, 2016",
            "top100_year": 2016,
            "top100_rank": 55
          },
          {
            "id": "410606",
            "winery_full": "Bodegas Cepa 21",
            "wine_full": "Ribera del Duero",
            "vintage": "2011",
            "note":
                "This aromatic red is graceful on the palate, with cherry, strawberry, licorice and vanilla notes mingling over light tannins, kept lively by bright acidity. This has a tender texture, but shows depth and focus. Drink now through 2021. 16,000 cases made.",
            "taster_initials": "TM",
            "color": "red",
            "country": "Spain",
            "region": "Spain",
            "score": 92,
            "price": 25,
            "issue_date": "Jun 15, 2016",
            "top100_year": 2016,
            "top100_rank": 56
          },
          {
            "id": "416281",
            "winery_full": "Cave de Roquebrun",
            "wine_full": "St.-Chinian-Roquebrun La Grange des Combes",
            "vintage": "2015",
            "note":
                "A muscular but polished red, with brooding blackberry pie, dark cherry and roasted plum notes complemented by iron, peppercorn and licorice details. Full but not overpowering tannins linger on the savory, herb-tinged finish. Syrah, Grenache and MourvÃ¨dre. Drink now through 2022. 12,000 cases made.",
            "taster_initials": "GS",
            "color": "red",
            "country": "France",
            "region": "Languedoc-Roussillon",
            "score": 91,
            "price": 20,
            "issue_date": "Nov 15, 2016",
            "top100_year": 2016,
            "top100_rank": 57
          },
          {
            "id": "416159",
            "winery_full": "Castello di Monsanto",
            "wine_full": "Chianti Classico Riserva",
            "vintage": "2013",
            "note":
                "Pure cherry takes center stage, framed by tar, earth, tobacco and mineral elements. Vivid and elegant, showing fine intensity and equilibrium, with a lingering aftertaste. Drink now through 2020. 17,000 cases imported.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 91,
            "price": 25,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 58
          },
          {
            "id": "420597",
            "winery_full": "ViÃ±a San Pedro",
            "wine_full": "Cabernet Sauvignon Maipo Valley 1865 Single Vineyard",
            "vintage": "2014",
            "note":
                "Rich and refined, with good cut to the red plum, crushed berry and raspberry flavors matched to notes of sandalwood and cardamom. Creamy midpalate, with a finish that's filled with chocolate and dark currant details. Drink now through 2021. 50,000 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Chile",
            "region": "Maipo",
            "score": 91,
            "price": 18,
            "issue_date": "Dec 15, 2016",
            "top100_year": 2016,
            "top100_rank": 59
          },
          {
            "id": "421555",
            "winery_full": "Roberto Anselmi",
            "wine_full": "Veneto White San Vincenzo",
            "vintage": "2015",
            "note":
                "An expressive white, creamy and lightly juicy throughout, offering flavors of blood orange granita, fresh tarragon, yellow peach and mineral, set in a light-bodied frame. The finish is juicy. Garganega with Sauvignon Blanc and Chardonnay. Drink now through 2019. 41,660 cases made.",
            "taster_initials": "AN",
            "color": "white",
            "country": "Italy",
            "region": "Veneto",
            "score": 90,
            "price": 18,
            "issue_date": "Nov 30, 2016",
            "top100_year": 2016,
            "top100_rank": 60
          },
          {
            "id": "412894",
            "winery_full": "Joseph Drouhin",
            "wine_full": "St.-VÃ©ran",
            "vintage": "2014",
            "note":
                "Though rich, this is offset by vivid acidity, creating a nice tension to the lemon, apple and melon flavors. Long and tangy on the finish. Drink now through 2018. 8,000 cases imported.",
            "taster_initials": "BS",
            "color": "white",
            "country": "France",
            "region": "Burgundy",
            "score": 90,
            "price": 19,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 61
          },
          {
            "id": "419768",
            "winery_full": "Bodegas OntaÃ±on",
            "wine_full": "Viura Rioja Vetiver",
            "vintage": "2014",
            "note":
                "This bold white marries expressive flavors to a muscular texture. Pear and quince notes mingle with brioche, chamomile and dried pineapple details, with juicy acidity and light tannins lending support. Lively now, this should harmonize with time. Drink now through 2024. 2,000 cases made.",
            "taster_initials": "TM",
            "color": "white",
            "country": "Spain",
            "region": "Spain",
            "score": 91,
            "price": 15,
            "issue_date": "Dec 15, 2016",
            "top100_year": 2016,
            "top100_rank": 62
          },
          {
            "id": "408833",
            "winery_full": "Tenute di EmÃ©ra",
            "wine_full": "Primitivo di Manduria Antica Masseria del Sigillo",
            "vintage": "2014",
            "note":
                "There's a rich, mouthfilling quality to this medium-bodied red, offering a velvety mix of spiced cherry, mulberry and herbed olive, with accents of mocha and graphite. Plush tannins show on the juicy finish. Drink now through 2021. 2,500 cases made.",
            "taster_initials": "AN",
            "color": "red",
            "country": "Italy",
            "region": "Puglia",
            "score": 90,
            "price": 17,
            "issue_date": "Apr 30, 2016",
            "top100_year": 2016,
            "top100_rank": 63
          },
          {
            "id": "408533",
            "winery_full": "Bodega ColomÃ©",
            "wine_full": "Malbec Salta AutÃ©ntico",
            "vintage": "2014",
            "note":
                "Fresh, rich and juicy, with lively raspberry, cherry and red plum flavors backed by fresh, crunchy acidity. Lengthens out nicely midpalate, showing mineral and pepper accents. Hints of slate and tangerine emerge on the complex finish. Drink now through 2020. 3,500 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Argentina",
            "region": "Salta",
            "score": 92,
            "price": 25,
            "issue_date": "May 31, 2016",
            "top100_year": 2016,
            "top100_rank": 64
          },
          {
            "id": "419672",
            "winery_full": "La Rioja Alta",
            "wine_full": "Rioja 904 Gran Reserva",
            "vintage": "2007",
            "note":
                "This supple red delivers bright, focused flavors of dried cherry, orange peel, vanilla, sandalwood, tobacco and spice, with light tannins and fresh acidity. An elegant rendering of the traditional style. Drink now through 2022. 12,500 cases made.",
            "taster_initials": "TM",
            "color": "red",
            "country": "Spain",
            "region": "Spain",
            "score": 93,
            "price": 55,
            "issue_date": "Dec 31, 2016",
            "top100_year": 2016,
            "top100_rank": 65
          },
          {
            "id": "416848",
            "winery_full": "Domaine HuÃ«t",
            "wine_full": "Vouvray Moelleux Clos du Bourg PremiÃ¨re Trie",
            "vintage": "2015",
            "note":
                "Concentrated, with a core of intense Jonagold apple, glazed Bosc pear, ginger cream and dried quince flavors, carried by filigreed acidity and backed by green tea, verbena, chamomile and persimmon notes. The finish is extremely long. Best from 2018 through 2040. 300 cases imported.",
            "taster_initials": "JM",
            "color": "dessert",
            "country": "France",
            "region": "Loire",
            "score": 97,
            "price": 70,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 66
          },
          {
            "id": "418410",
            "winery_full": "Hahn",
            "wine_full": "Pinot Noir Santa Lucia Highlands SLH",
            "vintage": "2014",
            "note":
                "The texture is plush, with lots of complex flavors, ranging from plum to anise to dusty, cedary oak. Satisfying from start to finish, ending with dusty, nutmeg-scented tannins. Drink now. 26,500 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Bay Area/Central Coast",
            "score": 92,
            "price": 30,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 67
          },
          {
            "id": "424549",
            "winery_full": "Lemelson",
            "wine_full": "Pinot Noir Willamette Valley Thea's Selection",
            "vintage": "2014",
            "note":
                "Polished, expressive and deftly balanced, this is generous with its baby powderâÂaccented cherry, lingonberry and floral flavors. Remains open and inviting through the long finish. Drink now through 2022. 9,950 cases made.",
            "taster_initials": "HS",
            "color": "red",
            "country": "Oregon",
            "region": "Oregon",
            "score": 92,
            "price": 30,
            "issue_date": "Dec 31, 2016",
            "top100_year": 2016,
            "top100_rank": 68
          },
          {
            "id": "415307",
            "winery_full": "CARM",
            "wine_full": "Douro Reserva",
            "vintage": "2012",
            "note":
                "Suave and rich, showing luscious sandalwood notes to the dried cherry and raspberry flavors. The creamy finish lingers with cocoa powder and white pepper accents. Drink now through 2020. 15,000 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Portugal",
            "region": "Portugal",
            "score": 91,
            "price": 22,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 69
          },
          {
            "id": "404785",
            "winery_full": "Ravines",
            "wine_full": "Riesling Finger Lakes Dry",
            "vintage": "2014",
            "note":
                "A taut, dry style, with pure lime, kiwifruit and pippin apple flavors backed by a slate note that gives the finish good tension and length. Very solid. Drink now through 2017. 5,475 cases made.",
            "taster_initials": "JM",
            "color": "white",
            "country": "New York",
            "region": "Finger Lakes",
            "score": 90,
            "price": 18,
            "issue_date": "Feb 29, 2016",
            "top100_year": 2016,
            "top100_rank": 70
          },
          {
            "id": "414460",
            "winery_full": "Two Hands",
            "wine_full": "Shiraz McLaren Vale Lily's Garden",
            "vintage": "2014",
            "note":
                "Notes of espresso and toasted hazelnut are rich and thick, with mocha-accented tannins that lend a velvety backdrop to the polished blackberry, licorice and black cherry flavors, lingering generously on the long finish. Drink now through 2030. 2,470 cases made.",
            "taster_initials": "MW",
            "color": "red",
            "country": "Australia",
            "region": "Australia",
            "score": 94,
            "price": 69,
            "issue_date": "Jul 31, 2016",
            "top100_year": 2016,
            "top100_rank": 71
          },
          {
            "id": "420052",
            "winery_full": "Jules Taylor",
            "wine_full": "Pinot Noir Marlborough",
            "vintage": "2015",
            "note":
                "Fragrant and ebullient, with caramel and vanilla bean accents to the core of ripe black cherry and plum flavors, balanced by velvety tannins and dark chocolate nuances. Expressive and generous on the long finish. Drink now through 2026. 2,000 cases made.",
            "taster_initials": "MW",
            "color": "red",
            "country": "New Zealand",
            "region": "New Zealand",
            "score": 93,
            "price": 19,
            "issue_date": "Oct 31, 2016",
            "top100_year": 2016,
            "top100_rank": 72
          },
          {
            "id": "412153",
            "winery_full": "Korbel",
            "wine_full": "Brut California Organic Grapes",
            "vintage": "NV",
            "note":
                "Crisp and luscious, this is a winning bubbly for a big party. Aromas of cinnamon, ginger and citrus lead to creamy flavors of pear and blanched almond. Drink now. 15,000 cases made.",
            "taster_initials": "TF",
            "color": "sparkling",
            "country": "California",
            "region": "Other California",
            "score": 90,
            "price": 14,
            "issue_date": "Jun 15, 2016",
            "top100_year": 2016,
            "top100_rank": 73
          },
          {
            "id": "421113",
            "winery_full": "Bodega Norton",
            "wine_full": "Malbec Mendoza Reserva",
            "vintage": "2014",
            "note":
                "This has a silky mouthfeel, with rich, plush flavors of boysenberry, dark currant and black olive that carry plenty of creamy accents. Features dark chocolate and Asian spice details on the finely textured finish. Drink now through 2020. 125,000 cases imported.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Argentina",
            "region": "Mendoza",
            "score": 90,
            "price": 19,
            "issue_date": "Nov 15, 2016",
            "top100_year": 2016,
            "top100_rank": 74
          },
          {
            "id": "416732",
            "winery_full": "Bodegas Godeval",
            "wine_full": "Valdeorras ViÃ±a Godeval Cepas Vellas",
            "vintage": "2014",
            "note":
                "Pear, peach and quince flavors mingle in this expressive white, while notes of mineral, tangerine and ginger add complexity. Shows depth and focus, with a clean, juicy finish. Drink now. 1,800 cases imported.",
            "taster_initials": "TM",
            "color": "white",
            "country": "Spain",
            "region": "Spain",
            "score": 91,
            "price": 20,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 75
          },
          {
            "id": "409547",
            "winery_full": "Carpineto",
            "wine_full": "Vino Nobile di Montepulciano Riserva",
            "vintage": "2011",
            "note":
                "A rich, powerful style, this evokes black cherry, black currant, plum, leather and tar flavors. Balanced and ready to enjoy, with lingering accents of spice and tobacco. Drink now through 2023. 15,000 cases made.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 93,
            "price": 31,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 76
          },
          {
            "id": "404941",
            "winery_full": "Bodegas Hidalgo La Gitana",
            "wine_full": "Oloroso Jerez Faraon",
            "vintage": "NV",
            "note":
                "Intense, with roasted almond, Brazil nut and walnut notes lending this a slightly burly aspect, while gunpowder tea, bitter orange and almond accents add a taut feel through the finish. This is a distinctive, edgy version that Sherry geeks will dig. Drink now. 1,500 cases made.",
            "taster_initials": "JM",
            "color": "white",
            "country": "Spain",
            "region": "Spain",
            "score": 92,
            "price": 27,
            "issue_date": "Feb 29, 2016",
            "top100_year": 2016,
            "top100_rank": 77
          },
          {
            "id": "415291",
            "winery_full": "Jean Perrier & Fils",
            "wine_full": "Savoie Apremont CuvÃ©e Gastronomie",
            "vintage": "2015",
            "note":
                "Yellow apple, fennel and lemon zest notes form the core, while lively floral and quinine accents stretch out the finish. Not big, but offers lovely cut and purity. Very refreshing. Drink now through 2017. 9,500 cases made.",
            "taster_initials": "JM",
            "color": "white",
            "country": "France",
            "region": "Savoie",
            "score": 90,
            "price": 16,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 78
          },
          {
            "id": "418044",
            "winery_full": "Tzora",
            "wine_full": "Judean Hills White",
            "vintage": "2014",
            "note":
                "Offers a spicy aroma, with pure, mineral-infused flavors of Granny Smith apple, lemon curd and pineapple, accented by notes of toasted coconut. The finish has crÃ¨me brÃ»lÃ©e hints that linger with plenty of richness. Chardonnay and Sauvignon Blanc. Kosher. Drink now through 2020. 2,000 cases made.",
            "taster_initials": "KM",
            "color": "white",
            "country": "Israel",
            "region": "Israel",
            "score": 92,
            "price": 30,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 79
          },
          {
            "id": "407656",
            "winery_full": "Lemos & van Zeller",
            "wine_full": "Douro Quinta Vale D. Maria",
            "vintage": "2013",
            "note":
                "Ripe, rich and lushly spiced, this muscular red features dark cherry and plum compote flavors that are accented by light pepper notes. Dark chocolate and cardamom accents show on the creamy finish. Drink now through 2022. 1,800 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Portugal",
            "region": "Portugal",
            "score": 94,
            "price": 68,
            "issue_date": "Apr 30, 2016",
            "top100_year": 2016,
            "top100_rank": 80
          },
          {
            "id": "415446",
            "winery_full": "ViÃ±a Cobos",
            "wine_full": "Chardonnay Mendoza Felino",
            "vintage": "2015",
            "note":
                "A richly spiced white, with focused, well-structured flavors of dried apple, ripe citrus and guava. Brioche notes show on the firm finish. Drink now through 2019. 4,500 cases imported.",
            "taster_initials": "KM",
            "color": "white",
            "country": "Argentina",
            "region": "Mendoza",
            "score": 90,
            "price": 21,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 81
          },
          {
            "id": "411321",
            "winery_full": "Kistler",
            "wine_full": "Chardonnay Carneros Hudson Vineyard",
            "vintage": "2013",
            "note":
                "Combines richness with a creamy texture, allowing the taut citrus, pear, melon and fig notes to fan out, gaining depth and length. Displays beautifully integrated smoky oak nuances. Drink now through 2020. 1,060 cases made.",
            "taster_initials": "JL",
            "color": "white",
            "country": "California",
            "region": "Carneros",
            "score": 94,
            "price": 80,
            "issue_date": "May 31, 2016",
            "top100_year": 2016,
            "top100_rank": 82
          },
          {
            "id": "420225",
            "winery_full": "Mud House",
            "wine_full": "Pinot Noir Central Otago",
            "vintage": "2014",
            "note":
                "Fleshy and appealing, with vibrant cherry and plum notes that have nutmeg and black tea flavors lingering on the finish. Offers good intensity and a velvety texture. Drink now through 2026. 1,000 cases imported.",
            "taster_initials": "MW",
            "color": "red",
            "country": "New Zealand",
            "region": "New Zealand",
            "score": 90,
            "price": 15,
            "issue_date": "Oct 31, 2016",
            "top100_year": 2016,
            "top100_rank": 83
          },
          {
            "id": "416597",
            "winery_full": "Boars' View",
            "wine_full": "Pinot Noir Sonoma Coast",
            "vintage": "2013",
            "note":
                "Bold, rich and assertive, with lively acidity and a tight, dense core of raspberry and blackberry, revealing rose, anise and spice scents. Supple, graceful and deep, this ends with a long, rich aftertaste and a supple, caressing texture. Drink now through 2024. 948 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Sonoma",
            "score": 95,
            "price": 125,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 84
          },
          {
            "id": "409881",
            "winery_full": "DomÃ¤ne Wachau",
            "wine_full": "GrÃ¼ner Veltliner Smaragd Trocken Wachau Terrassen",
            "vintage": "2013",
            "note":
                "Voluptuous and richly spiced, with some honeyed notes to the ripe apple, pear tart and glazed apricot flavors. Shows seductive smokiness midpalate, presenting a pastry-accented finish. Drink now through 2021. 6,000 cases made.",
            "taster_initials": "KM",
            "color": "white",
            "country": "Austria",
            "region": "NiederÃ¶sterreich",
            "score": 92,
            "price": 30,
            "issue_date": "May 31, 2016",
            "top100_year": 2016,
            "top100_rank": 85
          },
          {
            "id": "421557",
            "winery_full": "Vigneti del Vulture",
            "wine_full": "Aglianico del Vulture Piano del Cerro",
            "vintage": "2012",
            "note":
                "A dense and tarry red that glides on the silky palate, with mouthwatering acidity framing flavors of blueberry puree, chocolate-covered cherry, vanilla, dried thyme and oak spice. An expressive version in a modern style, yet refined and harmonious overall, with the grippy finish echoing the ripe fruit and tarry mineral character. Drink now through 2027. 5,000 cases made.",
            "taster_initials": "AN",
            "color": "red",
            "country": "Italy",
            "region": "Basilicata",
            "score": 93,
            "price": 36,
            "issue_date": "Dec 15, 2016",
            "top100_year": 2016,
            "top100_rank": 86
          },
          {
            "id": "417200",
            "winery_full": "A. Clape",
            "wine_full": "Cornas",
            "vintage": "2013",
            "note":
                "Dark and brooding, this has a deep well of black currant, fig and bitter plum fruit in reserve, shrouded for now in smoldering charcoal, bay leaf and alder notes. Tapenade and tar details hang in the background. Offers a steel beam of a finish. Tuck this away in the back corner of your cellar. Best from 2020 through 2035. 1,438 cases made.",
            "taster_initials": "JM",
            "color": "red",
            "country": "France",
            "region": "Northern RhÃ´ne",
            "score": 96,
            "price": 120,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 87
          },
          {
            "id": "412887",
            "winery_full": "Arnaldo Caprai",
            "wine_full": "Grechetto Colli Martani Grecante",
            "vintage": "2015",
            "note":
                "Thai basil and spice notes lace the creamy mix of Asian pear, white peach, stone and lemon zest in this well-knit white. Light- to medium-bodied and fresh, with a lingering, savory finish. Drink now through 2020. 10,800 cases made.",
            "taster_initials": "AN",
            "color": "white",
            "country": "Italy",
            "region": "Umbria",
            "score": 90,
            "price": 20,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 88
          },
          {
            "id": "412334",
            "winery_full": "D. Kourtakis",
            "wine_full": "Assyrtiko Santorini Greek Wine Cellars",
            "vintage": "2014",
            "note":
                "A creamy white, with notes of dried coconut to the ripe apple, baked pear and lemon curd flavors. The richly spiced finish features accents of dried mint and sage. Drink now through 2020. 10,000 cases made.",
            "taster_initials": "KM",
            "color": "white",
            "country": "Greece",
            "region": "Greece",
            "score": 90,
            "price": 20,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 89
          },
          {
            "id": "415758",
            "winery_full": "Domaines Bunan",
            "wine_full": "Bandol RosÃ© Moulin des Costes",
            "vintage": "2015",
            "note":
                "Offers a lovely combination of zip and richness, with creamy edges around a core of delicious white cherry and white peach flavors, all offset by a pure beam of minerality that pierces through from start to finish. Drink now through 2017. 4,000 cases made.",
            "taster_initials": "JM",
            "color": "blush",
            "country": "France",
            "region": "Provence",
            "score": 91,
            "price": 30,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 90
          },
          {
            "id": "416384",
            "winery_full": "Agricola Punica",
            "wine_full": "Isola dei Nuraghi Montessu",
            "vintage": "2014",
            "note":
                "An elegant version, with Asian five-spice powder and cherry blossom notes wafting through flavors of black raspberry preserves, bresaola and cured tobacco. Long and supple, presenting a mineral-tinged finish. Carignano, Syrah, Cabernet Sauvignon, Cabernet Franc and Merlot. Drink now through 2021. 12,500 cases made.",
            "taster_initials": "AN",
            "color": "red",
            "country": "Italy",
            "region": "Sardinia",
            "score": 90,
            "price": 30,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 91
          },
          {
            "id": "418071",
            "winery_full": "Philippe Alliet",
            "wine_full": "Chinon",
            "vintage": "2015",
            "note":
                "Lovely cherry pit, damson plum and violet notes stream through, picking up light savory and olive details along the way. The fresh finish features an iron echo. Very pure from start to finish. Drink now through 2020. 2,300 cases made.",
            "taster_initials": "JM",
            "color": "red",
            "country": "France",
            "region": "Loire",
            "score": 91,
            "price": 23,
            "issue_date": "Nov 30, 2016",
            "top100_year": 2016,
            "top100_rank": 92
          },
          {
            "id": "420659",
            "winery_full": "Galil Mountain",
            "wine_full": "Yiron Galilee",
            "vintage": "2013",
            "note":
                "A rich and plush red, with a deep well of blackberry pie, dark plum and hot stone flavors that fold together seamlessly. Creamy midpalate, presenting a finish that oozes with chocolate mousse and Asian spice details. Unctuous. Cabernet Sauvignon, Merlot, Syrah and Petit Verdot. Kosher. Drink now through 2020. 10,800 cases made.",
            "taster_initials": "KM",
            "color": "red",
            "country": "Israel",
            "region": "Israel",
            "score": 92,
            "price": 32,
            "issue_date": "Oct 15, 2016",
            "top100_year": 2016,
            "top100_rank": 93
          },
          {
            "id": "413009",
            "winery_full": "William FÃ¨vre",
            "wine_full": "Chablis Domaine",
            "vintage": "2014",
            "note":
                "This is delicate, featuring lemon, herb and stone flavors lifted by the fine acidity. Touches of seashore and oyster shell add depth as this coasts to a clean finish. Drink now through 2018. 4,000 cases imported.",
            "taster_initials": "BS",
            "color": "white",
            "country": "France",
            "region": "Burgundy",
            "score": 90,
            "price": 32,
            "issue_date": "Jun 30, 2016",
            "top100_year": 2016,
            "top100_rank": 94
          },
          {
            "id": "408568",
            "winery_full": "PlumpJack",
            "wine_full": "Syrah Napa Valley",
            "vintage": "2013",
            "note":
                "Well-built and richly structured, with bold aromas of blackberry, mocha and licorice, showing layered flavors of smoky raspberry, grilled herb and pepper. The tannins are big, but ripe and balanced. Drink now through 2028. 1,750 cases made.",
            "taster_initials": "TF",
            "color": "red",
            "country": "California",
            "region": "Napa",
            "score": 93,
            "price": 56,
            "issue_date": "Mar 31, 2016",
            "top100_year": 2016,
            "top100_rank": 95
          },
          {
            "id": "412499",
            "winery_full": "Nicolas-Jay",
            "wine_full": "Pinot Noir Willamette Valley",
            "vintage": "2014",
            "note":
                "Broad, expressive and light-footed, this brims with cherry, plum, licorice and cashew flavors that keep singing on the focused finish. Drink now through 2024. 1,750 cases made.",
            "taster_initials": "HS",
            "color": "red",
            "country": "Oregon",
            "region": "Oregon",
            "score": 93,
            "price": 65,
            "issue_date": "Jun 15, 2016",
            "top100_year": 2016,
            "top100_rank": 96
          },
          {
            "id": "415346",
            "winery_full": "Le Macchiole",
            "wine_full": "Bolgheri",
            "vintage": "2013",
            "note":
                "Sleek and elegant, with concentrated flavors of black cherry, black currant, cedar and vanilla. A wild, aromatic underbrush character lingers on the beefy finish. Merlot, Cabernet Franc and Syrah. Best from 2018 through 2024. 900 cases imported.",
            "taster_initials": "BS",
            "color": "red",
            "country": "Italy",
            "region": "Tuscany",
            "score": 91,
            "price": 34,
            "issue_date": "Aug 31, 2016",
            "top100_year": 2016,
            "top100_rank": 97
          },
          {
            "id": "420163",
            "winery_full": "Dakota Shy",
            "wine_full": "Cabernet Sauvignon Napa Valley",
            "vintage": "2014",
            "note":
                "Showcases Cabernet in a harmonious, graceful pose. Though big and rich, this is deftly balanced and easy to approach, with tiers of spicy black licorice, red and dark berry, mocha, mineral, sage and floral notes. Shows depth and dimension overall. Drink now through 2032. 800 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Napa",
            "score": 94,
            "price": 95,
            "issue_date": "Oct 31, 2016",
            "top100_year": 2016,
            "top100_rank": 98
          },
          {
            "id": "418400",
            "winery_full": "Cirq",
            "wine_full": "Pinot Noir Russian River Valley Treehouse",
            "vintage": "2013",
            "note":
                "Combining power and finesse, this is rich and extracted, with a supple yet gutsy core of mineral-laced tannins that weave into a mix of gravelly, loamy earth, juicy blackberry and wild berry. Drink now through 2022. 1,748 cases made.",
            "taster_initials": "JL",
            "color": "red",
            "country": "California",
            "region": "Sonoma",
            "score": 94,
            "price": 125,
            "issue_date": "Sep 30, 2016",
            "top100_year": 2016,
            "top100_rank": 99
          },
          {
            "id": "417455",
            "winery_full": "Louis Latour",
            "wine_full": "Corton-Charlemagne",
            "vintage": "2014",
            "note":
                "A broad, charming white, featuring lemon, baked apple, vanilla, clove and nutmeg flavors, with fine concentration and length. Shows a bright structure and chalky intensity on the slightly tannic finish. Best from 2019 through 2032. 3,100 cases made.",
            "taster_initials": "BS",
            "color": "white",
            "country": "France",
            "region": "Burgundy",
            "score": 95,
            "price": 175,
            "issue_date": "Dec 15, 2016",
            "top100_year": 2016,
            "top100_rank": 100
          }
        ]
